name: TestAppOnPR
on: [pull_request]
jobs:
  TestAndBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create env files
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          directory: back-end/
          file_name: .env.test
          fail_on_empty: true
      - name: Run tests
        run: docker-compose -f ./back-end/docker-compose.test.yml run node-app npm test
